/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author Mokleters
 */
public class dOKTER extends javax.swing.JFrame {

    /**
     * Creates new form dOKTER
     */
    public dOKTER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        WP = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        gd = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        kewarganegaraan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        DS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CB = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 70, 30);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setToolTipText("HI");
        jPanel1.setName("HI"); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setText("Waktu Praktek");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 310, 100, 14);

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 30, 70, 14);

        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 70, 60, 14);

        jLabel6.setText("Usia");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 110, 50, 14);

        jLabel7.setText("Jenis Kelamin");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 150, 80, 14);

        jLabel8.setText("Golongan Darah");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 190, 100, 14);

        jLabel9.setText("Status");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 230, 70, 14);

        jLabel10.setText("Kewarganegaraan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 270, 110, 14);
        jPanel1.add(WP);
        WP.setBounds(110, 300, 190, 30);
        jPanel1.add(nama);
        nama.setBounds(110, 20, 190, 30);
        jPanel1.add(alamat);
        alamat.setBounds(110, 60, 190, 30);
        jPanel1.add(usia);
        usia.setBounds(110, 100, 190, 30);
        jPanel1.add(jk);
        jk.setBounds(110, 140, 190, 30);
        jPanel1.add(gd);
        gd.setBounds(110, 180, 190, 30);
        jPanel1.add(status);
        status.setBounds(110, 220, 190, 30);
        jPanel1.add(kewarganegaraan);
        kewarganegaraan.setBounds(110, 260, 190, 30);

        jLabel11.setText("Dokter Spesialis");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 350, 100, 14);
        jPanel1.add(DS);
        DS.setBounds(110, 340, 190, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 110, 330, 390);
        jPanel1.getAccessibleContext().setAccessibleName("HI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Pemilihan Dokter");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 0, 240, 60);

        CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Dr. Tiara Pangestika", "Dr. Tiara Eka", "Dr. Tiara Mendes" }));
        CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBActionPerformed(evt);
            }
        });
        getContentPane().add(CB);
        CB.setBounds(110, 60, 150, 30);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 520);

        setBounds(0, 0, 416, 556);
    }// </editor-fold>//GEN-END:initComponents

    private void CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBActionPerformed
            
        if(CB.getSelectedItem().equals("Dr. Tiara Pangestika")){
            nama.setText("Dr. Tiara Pangestika");
            alamat.setText("Jalan Cintamu");
            usia.setText("20 Tahun");
            jk.setText("Ukhti");
            gd.setText("A");
            status.setText("Menikah");
            kewarganegaraan.setText("Madinah");
            WP.setText("Pagi (04.00 - 8.00)");
            DS.setText("Dokter Bedah");
        }
        else
            if(CB.getSelectedItem().equals("Dr. Tiara Eka")){
                nama.setText("Dr. Tiara Eka");
                alamat.setText("Fisabilillah");
                usia.setText("17 Tahun");
                jk.setText("Ukhti");
                gd.setText("O");
                status.setText("Jomblo Lillahita'ala");
                kewarganegaraan.setText("Syria");
                WP.setText("24 jam untukmu");
                DS.setText("Dokter Spesialis");
            }
        else
            if(CB.getSelectedItem().equals("Dr. Tiara Mendes")){
                nama.setText("Dr. Tiara Mendes");
                alamat.setText("Jalan menuju haram");
                usia.setText("10 Tahun");
                jk.setText("Ukhti");
                gd.setText("Allah");
                status.setText("otw ketemu jodoh");
                kewarganegaraan.setText("Makkah");
                WP.setText("Malam saja ya");
                DS.setText("Dokter umum");
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_CBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dOKTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dOKTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dOKTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dOKTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dOKTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB;
    private javax.swing.JTextField DS;
    private javax.swing.JTextField WP;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField gd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField kewarganegaraan;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField status;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
