
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class praktikum extends javax.swing.JFrame {

    /**
     * Creates new form praktikum
     */
    public praktikum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        day4 = new javax.swing.JButton();
        day1 = new javax.swing.JButton();
        day2 = new javax.swing.JButton();
        day3 = new javax.swing.JButton();
        day5 = new javax.swing.JButton();
        day6 = new javax.swing.JButton();
        day7 = new javax.swing.JButton();
        day8 = new javax.swing.JButton();
        day12 = new javax.swing.JButton();
        day9 = new javax.swing.JButton();
        day11 = new javax.swing.JButton();
        day10 = new javax.swing.JButton();
        day13 = new javax.swing.JButton();
        day15 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        day14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PHOTOGRAPHY CHALLENGE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 0, 380, 80);

        day4.setText("DAY 4");
        day4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day4ActionPerformed(evt);
            }
        });
        getContentPane().add(day4);
        day4.setBounds(320, 90, 73, 40);

        day1.setText("DAY 1");
        day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1ActionPerformed(evt);
            }
        });
        getContentPane().add(day1);
        day1.setBounds(30, 90, 70, 40);

        day2.setText("DAY 2");
        day2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2ActionPerformed(evt);
            }
        });
        getContentPane().add(day2);
        day2.setBounds(120, 90, 73, 40);

        day3.setText("DAY 3");
        day3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3ActionPerformed(evt);
            }
        });
        getContentPane().add(day3);
        day3.setBounds(220, 90, 73, 40);

        day5.setText("DAY 5");
        day5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day5ActionPerformed(evt);
            }
        });
        getContentPane().add(day5);
        day5.setBounds(30, 150, 70, 40);

        day6.setText("DAY 6");
        day6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day6ActionPerformed(evt);
            }
        });
        getContentPane().add(day6);
        day6.setBounds(120, 150, 73, 40);

        day7.setText("DAY 7");
        getContentPane().add(day7);
        day7.setBounds(220, 150, 73, 40);

        day8.setText("DAY 8");
        getContentPane().add(day8);
        day8.setBounds(320, 150, 73, 40);

        day12.setText("DAY 12");
        getContentPane().add(day12);
        day12.setBounds(320, 210, 73, 40);

        day9.setText("DAY 9");
        getContentPane().add(day9);
        day9.setBounds(30, 210, 70, 40);

        day11.setText("DAY 11");
        getContentPane().add(day11);
        day11.setBounds(220, 210, 73, 40);

        day10.setText("DAY 10");
        getContentPane().add(day10);
        day10.setBounds(120, 210, 73, 40);

        day13.setText("DAY 13");
        getContentPane().add(day13);
        day13.setBounds(30, 270, 70, 40);

        day15.setText("DAY 15");
        getContentPane().add(day15);
        day15.setBounds(220, 270, 73, 40);

        jButton15.setText("CLOSE");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(320, 270, 73, 40);

        day14.setText("DAY 14");
        getContentPane().add(day14);
        day14.setBounds(120, 270, 73, 40);

        setBounds(0, 0, 453, 373);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1ActionPerformed
        
        String day1;
        JOptionPane.showMessageDialog(null, "Self Potrait");
// TODO add your handling code here:
    }//GEN-LAST:event_day1ActionPerformed

    private void day2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2ActionPerformed
       
    String day2;
    JOptionPane.showMessageDialog(null, "Animal");
// TODO add your handling code here:
    }//GEN-LAST:event_day2ActionPerformed

    private void day3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3ActionPerformed
      String day3;
    JOptionPane.showMessageDialog(null, "Sky");  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_day3ActionPerformed

    private void day4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day4ActionPerformed
        
        String day4;
    JOptionPane.showMessageDialog(null, "Light");
        // TODO add your handling code here:
    }//GEN-LAST:event_day4ActionPerformed

    private void day5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day5ActionPerformed
    String day5;
    JOptionPane.showMessageDialog(null, "Dark");
        // TODO add your handling code here:
    }//GEN-LAST:event_day5ActionPerformed

    private void day6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day6ActionPerformed
        String day6;
    JOptionPane.showMessageDialog(null, "Nature");

        // TODO add your handling code here:
    }//GEN-LAST:event_day6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(praktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new praktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton day1;
    private javax.swing.JButton day10;
    private javax.swing.JButton day11;
    private javax.swing.JButton day12;
    private javax.swing.JButton day13;
    private javax.swing.JButton day14;
    private javax.swing.JButton day15;
    private javax.swing.JButton day2;
    private javax.swing.JButton day3;
    private javax.swing.JButton day4;
    private javax.swing.JButton day5;
    private javax.swing.JButton day6;
    private javax.swing.JButton day7;
    private javax.swing.JButton day8;
    private javax.swing.JButton day9;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
